<?php
/* @var string|null $csrfToken */
/* @var int|null $id */
/* @var string|null $title */
/* @var string|null $slug */
/* @var string|null $text */
/* @var string|null $summary */
/* @var string|null $metaTitle */
/* @var string|null $metaDescription */
/* @var int|null $topicId */
/* @var bool $isActive */
/* @var array|null $topics */
/* @var array|null $tags */
/* @var array|null $errors */

$formAction = '/admin/article/';

if (!empty($id)) {
    $formAction = sprintf('/admin/article/%d/', $id);
}
?>
<div class="form-wrapper">
    <?php if (empty($id)): ?>
        <h1>Add New Article</h1>
    <?php else: ?>
        <h1>Edit Article</h1>
    <?php endif; ?>
    <?php if (!empty($errors)): ?>
        <div class="errors">
            <?php foreach ($errors as $error): ?>
                <p>
                    <?= $error; ?>
                </p>
            <?php endforeach; ?>
        </div>
    <?php endif; ?>
    <form action="<?= $formAction; ?>"
          enctype="multipart/form-data"
          method="POST">
        <p>
            <label for="title" class="label-input-wrapper">
                <input type="text"
                       name="title"
                       id="title"
                       placeholder="Title"
                       value="<?= $title; ?>">
            </label>
        </p>
        <p>
            <label for="slug" class="label-input-wrapper">
                <input type="text"
                       name="slug"
                       id="slug"
                       placeholder="Slug"
                       value="<?= $slug; ?>">
            </label>
        </p>
        <p>
            <label for="summary" class="label-input-wrapper">
                <textarea name="summary"
                          id="summary"
                          placeholder="Summary">
                    <?= $summary ?>
                </textarea>
            </label>
        </p>
        <p>
            <label for="text" class="label-input-wrapper">
                <textarea name="text"
                          id="text"
                          placeholder="Text">
                    <?= $text ?>
                </textarea>
            </label>
        </p>
        <p>
            <label for="meta-title" class="label-input-wrapper">
                <input type="text"
                       name="meta_title"
                       id="meta-title"
                       placeholder="Meta title"
                       value="<?= $metaTitle; ?>">
            </label>
        </p>
        <p>
            <label for="meta-description" class="label-input-wrapper">
                <textarea name="meta_description"
                          id="meta-description"
                          placeholder="Meta Description">
                    <?= $metaDescription ?>
                </textarea>
            </label>
        </p>
        <p>
            Topics
            <?php foreach ($tags as $tag): ?>
                <?php
                /*
                    <input type="checkbox"
                       name="is_active"
                       id="is_active"
                       value="1"
                    <?= $checked ?>>
                <label for="is_active">
                    Is Active
                </label>
                */
                ?>
            <?php endforeach; ?>
        </p>
        <p>
            Tags
            <?php foreach ($tags as $tag): ?>
            <?php
            /*
                <input type="checkbox"
                   name="is_active"
                   id="is_active"
                   value="1"
                <?= $checked ?>>
            <label for="is_active">
                Is Active
            </label>
            */
            ?>
            <?php endforeach; ?>
        </p>
        <p>
            <?php
            $checked = $isActive ? ' checked' : '';
            ?>
            <input type="checkbox"
                   name="is_active"
                   id="is_active"
                   value="1"
                <?= $checked ?>>
            <label for="is_active">
                Is Active
            </label>
        </p>
        <p>
            <input type="submit" value="save">
        </p>
        <input type="hidden" name="csrf_token" value="<?= $csrfToken ?>">
        <input type="hidden" name="id" value="<?= $id; ?>">
    </form>
</div>
