<?php

use Sonder\Models\Article\ArticleValuesObject;

/* @var ArticleValuesObject[]|null $articles */
?>
<p>
    <span>Articles</span> /
    <a href="/admin/articles/comments/">Comments</a> /
    <a href="/admin/articles/hits/">Hits</a>
</p>
<p>
    <a href="/admin/article/" class="button">New Article</a>
</p>
<?php if (empty($articles)): ?>
    <p>
        Empty
    </p>
<?php else: ?>
    <table>
        <tbody>
        <tr>
            <th class="fixed-cell hide-on-mobile">ID</th>
            <th>Title</th>
            <th class="hide-on-mobile">Slug</th>
            <th class="hide-on-mobile">Topic</th>
            <th class="hide-on-tablet">Is Active</th>
            <th class="hide-on-mobile">Created At</th>
            <th class="hide-on-tablet">Updated At</th>
            <th class="hide-on-tablet">Removed At</th>
            <th colspan="3"></th>
        </tr>
        <?php foreach ($articles as $article): ?>
            <?php
            $articleIsActive = $article->getIsActive() ? 'Yes' : 'No';

            $articleCdate = $article->getCdate('Y-m-d H:i:s');

            $articleTopic = '---';

            $articleMdate = '---';
            $articleDdate = '---';

            if (!empty($article->getTopicVO())) {
                $articleTopic = sprintf(
                    '<a href="%s">%s</a>',
                    $article->getTopicVO()->getAdminViewLink(),
                    $article->getTopicVO()->getTitle()
                );
            }

            if (!empty($article->getMdate())) {
                $articleMdate = $article->getMdate('Y-m-d H:i:s');
            }

            if (!empty($article->getDdate())) {
                $articleDdate = $article->getDdate('Y-m-d H:i:s');
            }
            ?>
            <?php if ($article->isRemoved()): ?>
                <tr class="list-item-removed">
            <?php else: ?>
                <tr>
            <?php endif; ?>
            <td class="hide-on-mobile"><?= $article->getId() ?></td>
            <td><?= $article->getTitle() ?></td>
            <td class="hide-on-mobile"><?= $article->getSlug() ?></td>
            <td class="hide-on-mobile"><?= $articleTopic ?></td>
            <td class="hide-on-tablet"><?= $articleIsActive ?></td>
            <td class="hide-on-mobile"><?= $articleCdate ?></td>
            <td class="hide-on-tablet"><?= $articleMdate ?></td>
            <td class="hide-on-tablet"><?= $articleDdate ?></td>
            <td>
                <a href="<?= $article->getAdminViewLink() ?>">
                    <i class="fas fa-eye"></i>
                </a>
            </td>
            <td>
                <a href="<?= $article->getEditLink() ?>">
                    <i class="fas fa-edit"></i>
                </a>
            </td>
            <td>
                <?php if ($article->isRemoved()): ?>
                    <a href="<?= $article->getRestoreLink() ?>">
                        <i class="fas fa-reply"></i>
                    </a>
                <?php else: ?>
                    <a href="<?= $article->getRemoveLink() ?>">
                        <i class="fas fa-trash-alt"></i>
                    </a>
                <?php endif; ?>
            </td>
            </tr>
        <?php endforeach; ?>
        <tr>
            <th class="fixed-cell hide-on-mobile">ID</th>
            <th>Title</th>
            <th class="hide-on-mobile">Slug</th>
            <th class="hide-on-mobile">Topic</th>
            <th class="hide-on-tablet">Is Active</th>
            <th class="hide-on-mobile">Created At</th>
            <th class="hide-on-tablet">Updated At</th>
            <th class="hide-on-tablet">Removed At</th>
            <th colspan="3"></th>
        </tr>
        </tbody>
    </table>
<?php endif; ?>
<?php if (!empty($pagination)): ?>
    <div class="pagination">
        <?= $pagination ?>
    </div>
<?php endif; ?>
