<?php
/* @var ArticleValuesObject $article */

use Sonder\Models\Article\ArticleValuesObject;

use function Sonder\__t;

?>
<?php foreach ([0, 1, 3, 4, 5] as $tmp) : ?>
    <div class="post">
        <h2 class="post-list-item-title post-js-link"
            data-url="<?= $article->getLink(); ?>">
            <?= $article->getTitle(); ?>
        </h2>
        <p>
        <span class="article-meta">
            <span class="article-meta-image-wrapper post-js-link"
                  data-url="<?= $article->getLink(); ?>">
                <img src="<?= ''//$article->getMedia('list');    ?>"
                     alt="<?= $article->getTitle(); ?>">
            </span>
            <span class="article-meta-date post-js-link"
                  data-url="<?= $article->getLink(); ?>">
                <?= $article->getCdate('Y-m-d'); ?>
            </span>
            <?php if (false && !empty($article->getTopic())): ?>
                <span class="article-meta-topic">
                    <a href="<?= 'TEST TOPIC LINK'//$article->getTopic()
                    //->getLink();    ?>">
                        <i class="fas fa-tag"></i>
                        <?= 'TEST TOPIC'//$article->getTopic()->getTitle();    ?>
                    </a>
                </span>
            <?php endif; ?>
        </span>
            <span class="post-js-link"
                  data-url="<?= $article->getLink(); ?>">
            <?= $article->getSummary(); ?>
        </span>
            <a href="<?= $article->getLink(); ?>" class="article-read-more">
                <?= __t('Read more'); ?>
            </a>
        </p>
    </div>
<?php endforeach; ?>
<!-- TODO -->
