<div class="form-wrapper">
    <form action="/admin/login/" method="POST" class="login-form">
        <p class="login-image-wrapper">
            <a href="/">
                <img src="/assets/img/login.png"
                     alt="login"
                     class="login-image">
            </a>
        </p>
        <?php if (!empty($errors)): ?>
            <p>
                <?php foreach ($errors as $error): ?>
                    <?= $error; ?><br>
                <?php endforeach; ?>
            </p>
        <?php endif; ?>
        <p>
            <input type="text" name="login" placeholder="Login" value="">
        </p>
        <p>
            <input type="password" name="password" placeholder="Password">
        </p>
        <p>
            <input type="submit" value="Login">
        </p>
    </form>
</div>