<?php

use Sonder\Models\User\SignInForm;

/* @var string|null $csrfToken */
/* @var array|null $errors */
/* @var SignInForm $form */

?>
<div class="form-wrapper">
    <form action="/admin/login/" method="POST" class="login-form">
        <p class="login-image-wrapper">
            <a href="/">
                <img src="/assets/img/admin/login.png"
                     alt="login"
                     class="login-image">
            </a>
        </p>
        <?php if (!empty($errors)): ?>
            <p>
                <?php foreach ($errors as $error): ?>
                    <?= $error; ?><br>
                <?php endforeach; ?>
            </p>
        <?php endif; ?>
        <p>
            <input type="text"
                   name="login"
                   placeholder="Login"
                   value="<?= $form->getLogin() ?>">
        </p>
        <p>
            <input type="password"
                   name="password"
                   placeholder="Password"
                   value="<?= $form->getPassword() ?>">
        </p>
        <p>
            <input type="submit" value="Login">
        </p>
        <input type="hidden" name="csrf_token" value="<?= $csrfToken ?>">
    </form>
</div>