<?php
/* @var string|null $csrfToken */
/* @var int|null $id */
/* @var int|null $parentId */
/* @var string|null $name */
/* @var array|null $allowedActions */
/* @var array|null $deniedActions */
/* @var array|null $roles */
/* @var array|null $roleActions */
/* @var bool $isActive */
/* @var array|null $errors */

$formAction = '/admin/users/role/';

if (!empty($id)) {
    $formAction = sprintf('/admin/users/role/%d/', $id);
}
?>
<div class="form-wrapper">
    <?php if (!empty($errors)): ?>
        <div class="errors">
            <?php foreach ($errors as $error): ?>
                <p>
                    <?= $error; ?>
                </p>
            <?php endforeach; ?>
        </div>
    <?php endif; ?>
    <form action="<?= $formAction; ?>"
          enctype="multipart/form-data"
          method="POST">
        <p>
            <label>
                <input type="text"
                       name="name"
                       placeholder="Name"
                       value="<?= $name; ?>">
            </label>
        </p>
        <p>
            <label>
                <select name="parent_id">
                    <?php
                    $selected = empty($parentId) ? ' selected="selected"' : '';
                    ?>
                    <option value="0" disabled<?= $selected; ?>>
                        Parent
                    </option>
                    <?php if (!empty($roles)): ?>
                        <?php foreach ($roles as $role): ?>
                            <?php
                            $selected = '';
                            if ($role->getId() == $parentId) {
                                $selected = ' selected';
                            }
                            ?>
                            <option value="<?= $role->getId(); ?>"
                                <?= $selected; ?>>
                                <?= $role->getName(); ?>
                            </option>
                        <?php endforeach; ?>
                    <?php endif; ?>
                </select>
            </label>
        </p>
        <?php if (!empty($roleActions)): ?>
            <p>
                <span>Allowed actions</span>
                <br>
                <?php foreach ($roleActions as $roleAction): ?>
                    <?php
                    $roleActionId = $roleAction->getId();

                    $checked = '';

                    if (in_array($roleActionId, $allowedActions)) {
                        $checked = ' checked';
                    }
                    ?>
                    <input type="checkbox"
                           name="allowed_actions[]"
                           value="<?= $roleActionId; ?>"
                           id="allowed-action-input-<?= $roleActionId; ?>"
                        <?= $checked; ?>>
                    <label for="allowed-action-input-<?= $roleActionId; ?>">
                        <?= $roleAction->getName(); ?>
                    </label>
                    <br>
                <?php endforeach; ?>
            </p>
            <p>
                <span>Denied actions</span>
                <br>
                <?php foreach ($roleActions as $roleAction): ?>
                    <?php
                    $roleActionId = $roleAction->getId();

                    $checked = '';

                    if (in_array($roleActionId, $allowedActions)) {
                        $checked = ' checked';
                    }
                    ?>
                    <input type="checkbox"
                           name="denied_actions[]"
                           value="<?= $roleActionId; ?>"
                           id="denied-action-input-<?= $roleActionId; ?>"
                        <?= $checked; ?>>
                    <label for="denied-action-input-<?= $roleActionId; ?>">
                        <?= $roleAction->getName(); ?>
                    </label>
                    <br>
                <?php endforeach; ?>
            </p>
        <?php endif; ?>
        <p>
            <?php
            $checked = $isActive ? ' checked' : '';
            ?>
            <label>
                <input type="checkbox"
                       name="is_active"
                       value="1"
                    <?= $checked ?>>
            </label>
            Is Active
        </p>
        <p>
            <input type="submit" value="save">
        </p>
        <input type="hidden" name="csrf_token" value="<?= $csrfToken ?>">
        <input type="hidden" name="id" value="<?= $id; ?>">
    </form>
</div>
