<?php

use Sonder\Models\Role\RoleValuesObject;

/* @var RoleValuesObject[]|null $roles */
?>
<p>
    <a href="/admin/users/">Users</a> /
    <span>Roles</span> /
    <a href="/admin/users/roles/actions/">Actions</a>
</p>
<p>
    <a href="/admin/users/role/" class="button">New role</a>
</p>
<?php if (empty($roles)): ?>
    <p>
        Empty
    </p>
<?php else: ?>
    <table>
        <tbody>
        <tr>
            <th class="fixed-cell hide-on-mobile">ID</th>
            <th>Name</th>
            <th class="hide-on-mobile">Parent</th>
            <th class="hide-on-tablet">Allowed actions</th>
            <th class="hide-on-tablet">Denied actions</th>
            <th class="hide-on-tablet">Is System</th>
            <th class="hide-on-tablet">Is Active</th>
            <th class="hide-on-mobile">Created At</th>
            <th class="hide-on-tablet">Updated At</th>
            <th class="hide-on-tablet">Removed At</th>
            <th colspan="2"></th>
        </tr>
        <?php foreach ($roles as $role): ?>
            <?php
            $roleIsActive = $role->getIsActive() ? 'Yes' : 'No';

            $roleIsSystem = $role->getIsSystem() ? 'Yes' : 'No';

            $roleCdate = $role->getCdate('Y-m-d H:i:s');

            $roleParent = '---';

            $roleMdate = '---';
            $roleDdate = '---';

            $allowedActions = $role->getAllowedActions();
            $deniedActions = $role->getDeniedActions();

            if (!empty($allowedActions)) {
                $allowedActions = implode('<br><br>', $allowedActions);
            }

            if (!empty($deniedActions)) {
                $deniedActions = implode('<br><br>', $deniedActions);
            }

            if (!empty($role->getParentVO())) {
                $roleParent = sprintf(
                    '%s (ID: %d)',
                    $role->getParentVO()->getName(),
                    $role->getParentVO()->getId()
                );
            }

            if (!empty($role->getMdate())) {
                $roleMdate = $role->getMdate('Y-m-d H:i:s');
            }

            if (!empty($role->getDdate())) {
                $roleDdate = $role->getDdate('Y-m-d H:i:s');
            }
            ?>
            <?php if ($role->isRemoved()): ?>
                <tr class="list-item-removed">
            <?php else: ?>
                <tr>
            <?php endif; ?>
            <td class="hide-on-mobile"><?= $role->getId() ?></td>
            <td><?= $role->getName() ?></td>
            <td class="hide-on-mobile"><?= $roleParent ?></td>
            <td class="hide-on-tablet"><?= $allowedActions ?></td>
            <td class="hide-on-tablet"><?= $deniedActions ?></td>
            <td class="hide-on-tablet"><?= $roleIsSystem ?></td>
            <td class="hide-on-tablet"><?= $roleIsActive ?></td>
            <td class="hide-on-mobile"><?= $roleCdate ?></td>
            <td class="hide-on-tablet"><?= $roleMdate ?></td>
            <td class="hide-on-tablet"><?= $roleDdate ?></td>
            <?php if ($role->getIsSystem()): ?>
                <td colspan="2">---</td>
            <?php else: ?>
                <td>
                    <a href="<?= $role->getEditLink() ?>">
                        <i class="fas fa-edit"></i>
                    </a>
                </td>
                <td>
                    <?php if ($role->isRemoved()): ?>
                        <a href="<?= $role->getRestoreLink() ?>">
                            <i class="fas fa-reply"></i>
                        </a>
                    <?php else: ?>
                        <a href="<?= $role->getRemoveLink() ?>">
                            <i class="fas fa-trash-alt"></i>
                        </a>
                    <?php endif; ?>
                </td>
            <?php endif; ?>
            </tr>
        <?php endforeach; ?>
        <tr>
            <th class="fixed-cell hide-on-mobile">ID</th>
            <th>Name</th>
            <th class="hide-on-mobile">Parent</th>
            <th class="hide-on-tablet">Allowed actions</th>
            <th class="hide-on-tablet">Denied actions</th>
            <th class="hide-on-tablet">Is System</th>
            <th class="hide-on-tablet">Is Active</th>
            <th class="hide-on-mobile">Created At</th>
            <th class="hide-on-tablet">Updated At</th>
            <th class="hide-on-tablet">Removed At</th>
            <th colspan="2"></th>
        </tr>
        </tbody>
    </table>
<?php endif; ?>
<?php if (!empty($pagination)): ?>
    <div class="pagination">
        <?= $pagination ?>
    </div>
<?php endif; ?>
