<?php
/* @var string|null $csrfToken */
/* @var int|null $id */
/* @var string|null $title */
/* @var string|null $slug */
/* @var bool $isActive */
/* @var array|null $errors */

$formAction = '/admin/tag/';

if (!empty($id)) {
    $formAction = sprintf('/admin/tag/%d/', $id);
}
?>
<div class="form-wrapper">
    <?php if (empty($id)): ?>
        <h1>Add New Tag</h1>
    <?php else: ?>
        <h1>Edit tag</h1>
    <?php endif; ?>
    <?php if (!empty($errors)): ?>
        <div class="errors">
            <?php foreach ($errors as $error): ?>
                <p>
                    <?= $error; ?>
                </p>
            <?php endforeach; ?>
        </div>
    <?php endif; ?>
    <form action="<?= $formAction; ?>"
          enctype="multipart/form-data"
          method="POST">
        <p>
            <label for="name" class="label-input-wrapper">
                <input type="text"
                       name="title"
                       placeholder="Title"
                       value="<?= $title; ?>">
            </label>
        </p>
        <p>
            <label for="name" class="label-input-wrapper">
                <input type="text"
                       name="slug"
                       placeholder="Slug"
                       value="<?= $slug; ?>">
            </label>
        </p>
        <p>
            <?php
            $checked = $isActive ? ' checked' : '';
            ?>
            <input type="checkbox"
                   name="is_active"
                   value="1"
                <?= $checked ?>>
            <label for="is_active">
                Is Active
            </label>
        </p>
        <p>
            <input type="submit" value="save">
        </p>
        <input type="hidden" name="csrf_token" value="<?= $csrfToken ?>">
        <input type="hidden" name="id" value="<?= $id; ?>">
    </form>
</div>
