<?php

use Sonder\Models\Tag\TagValuesObject;

/* @var TagValuesObject[]|null $tags */
?>
<p>
    <span>Tags</span> /
    <a href="/admin/taxonomy/topics/">Topics</a>
</p>
<p>
    <a href="/admin/taxonomy/tag/" class="button">New Tag</a>
</p>
<?php if (empty($tags)): ?>
    <p>
        Empty
    </p>
<?php else: ?>
    <table>
        <tbody>
        <tr>
            <th class="fixed-cell hide-on-mobile">ID</th>
            <th>Title</th>
            <th class="hide-on-mobile">Slug</th>
            <th class="hide-on-tablet">Is Active</th>
            <th class="hide-on-mobile">Created At</th>
            <th class="hide-on-tablet">Updated At</th>
            <th class="hide-on-tablet">Removed At</th>
            <th colspan="3"></th>
        </tr>
        <?php foreach ($tags as $tag): ?>
            <?php
            $tagIsActive = $tag->isActive() ? 'Yes' : 'No';

            $tagCdate = $tag->getCdate('Y-m-d H:i:s');

            $tagMdate = '---';
            $tagDdate = '---';

            if (!empty($tag->getMdate())) {
                $tagMdate = $tag->getMdate('Y-m-d H:i:s');
            }

            if (!empty($tag->getDdate())) {
                $tagDdate = $tag->getDdate('Y-m-d H:i:s');
            }
            ?>
            <?php if ($tag->isRemoved()): ?>
                <tr class="list-item-removed">
            <?php else: ?>
                <tr>
            <?php endif; ?>
            <td class="hide-on-mobile"><?= $tag->getId() ?></td>
            <td><?= $tag->getTitle() ?></td>
            <td class="hide-on-mobile"><?= $tag->getSlug() ?></td>
            <td class="hide-on-tablet"><?= $tagIsActive ?></td>
            <td class="hide-on-mobile"><?= $tagCdate ?></td>
            <td class="hide-on-tablet"><?= $tagMdate ?></td>
            <td class="hide-on-tablet"><?= $tagDdate ?></td>
            <td>
                <a href="<?= $tag->getAdminViewLink() ?>">
                    <i class="fas fa-eye"></i>
                </a>
            </td>
            <td>
                <a href="<?= $tag->getEditLink() ?>">
                    <i class="fas fa-edit"></i>
                </a>
            </td>
            <td>
                <?php if ($tag->isRemoved()): ?>
                    <a href="<?= $tag->getRestoreLink() ?>">
                        <i class="fas fa-reply"></i>
                    </a>
                <?php else: ?>
                    <a href="<?= $tag->getRemoveLink() ?>">
                        <i class="fas fa-trash-alt"></i>
                    </a>
                <?php endif; ?>
            </td>
            </tr>
        <?php endforeach; ?>
        <tr>
            <th class="fixed-cell hide-on-mobile">ID</th>
            <th>Title</th>
            <th class="hide-on-mobile">Slug</th>
            <th class="hide-on-tablet">Is Active</th>
            <th class="hide-on-mobile">Created At</th>
            <th class="hide-on-tablet">Updated At</th>
            <th class="hide-on-tablet">Removed At</th>
            <th colspan="3"></th>
        </tr>
        </tbody>
    </table>
<?php endif; ?>
<?php if (!empty($pagination)): ?>
    <div class="pagination">
        <?= $pagination ?>
    </div>
<?php endif; ?>
