<?php
/* @var string|null $csrfToken */
/* @var int|null $id */
/* @var string|null $name */
/* @var bool $isActive */
/* @var array|null $errors */

$formAction = '/admin/users/roles/action/';

if (!empty($id)) {
    $formAction = sprintf('/admin/users/roles/action/%d/', $id);
}
?>
<p>
    <a href="/admin/users/">Users</a> /
    <a href="/admin/users/roles/">Roles</a> /
    <a href="/admin/users/roles/actions/">Actions</a>
</p>
<?php if (empty($id)): ?>
    <h1>Add New Role Action</h1>
<?php else: ?>
    <h1>Edit Role Action</h1>
<?php endif; ?>
<div class="form-wrapper">
    <?php if (!empty($errors)): ?>
        <div class="errors">
            <?php foreach ($errors as $error): ?>
                <p>
                    <?= $error; ?>
                </p>
            <?php endforeach; ?>
        </div>
    <?php endif; ?>
    <form action="<?= $formAction; ?>"
          enctype="multipart/form-data"
          method="POST">
        <p>
            <label for="name" class="label-input-wrapper">
                <input type="text"
                       name="name"
                       placeholder="Name"
                       value="<?= $name; ?>">
            </label>
        </p>
        <p>
            <?php
            $checked = $isActive ? ' checked' : '';
            ?>
            <input type="checkbox"
                   name="is_active"
                   value="1"
                   id="is-active-input"
                <?= $checked ?>>
            <label for="is-active-input">Is Active</label>
        </p>
        <p>
            <input type="submit" value="save">
        </p>
        <input type="hidden" name="csrf_token" value="<?= $csrfToken ?>">
        <input type="hidden" name="id" value="<?= $id; ?>">
    </form>
</div>
