<form itemprop="potentialAction"
      itemid="site-search-form"
      itemscope
      itemtype="https://schema.org/SearchAction"
      action="/search/"
      method="GET"
      id="search-form"
      class="search-form">
    <meta itemprop="target"
          content="#"/>
    <input itemprop="query-input"
           type="text"
           name="keyword"
           placeholder="Search"
           id="search-input">
</form>