<?php
/* @var string $currentUrl */
?>
<ul class="main-menu">
    <li>
        <?php if ($currentUrl == '/admin/'): ?>
            <a href="/admin/" class="main-menu-link-active">Admin</a>
        <?php else: ?>
            <a href="/admin/">Admin</a>
        <?php endif; ?>
    </li>
    <li>
        <?php if (preg_match('/^\/admin\/user.*?$/su', $currentUrl)): ?>
            <a href="/admin/users/" class="main-menu-link-active">Users</a>
        <?php else: ?>
            <a href="/admin/users/">Users</a>
        <?php endif; ?>
    </li>
    <li>
        <?php if (preg_match('/^\/admin\/taxonomy.*?$/su', $currentUrl)): ?>
            <a href="/admin/taxonomy/"
               class="main-menu-link-active">Taxonomy</a>
        <?php else: ?>
            <a href="/admin/taxonomy/">Taxonomy</a>
        <?php endif; ?>
    </li>
    <li>
        <?php if (preg_match('/^\/admin\/articles.*?$/su', $currentUrl)): ?>
            <a href="/admin/articles/"
               class="main-menu-link-active">
                Articles
            </a>
        <?php else: ?>
            <a href="/admin/articles/">Articles</a>
        <?php endif; ?>
    </li>
    <li>
        <?php if (preg_match('/^\/admin\/settings.*?$/su', $currentUrl)): ?>
            <a href="/admin/settings/" class="main-menu-link-active">Setting</a>
        <?php else: ?>
            <a href="/admin/settings/">Setting</a>
        <?php endif; ?>
    </li>
    <li>
        <a href="/admin/logout/">Logout</a>
    </li>
</ul>
