<?php
/* @var string|null $csrfToken */
/* @var int|null $id */
/* @var int|null $parentId */
/* @var array $topics */
/* @var string|null $title */
/* @var string|null $slug */
/* @var string|null $image */
/* @var bool $isActive */
/* @var array|null $errors */

$formAction = '/admin/taxonomy/topic/';

if (!empty($id)) {
    $formAction = sprintf('/admin/taxonomy/topic/%d/', $id);
}
?>
<p>
    <a href="/admin/taxonomy/tags/">Tags</a> /
    <a href="/admin/taxonomy/topics/">Topics</a>
</p>
<div class="form-wrapper">
    <?php if (empty($id)): ?>
        <h1>Add New Topic</h1>
    <?php else: ?>
        <h1>Edit Topic</h1>
    <?php endif; ?>
    <?php if (!empty($errors)): ?>
        <div class="errors">
            <?php foreach ($errors as $error): ?>
                <p>
                    <?= $error; ?>
                </p>
            <?php endforeach; ?>
        </div>
    <?php endif; ?>
    <form action="<?= $formAction; ?>"
          enctype="multipart/form-data"
          method="POST">
        <?php if (!empty($id) && !empty($image)): ?>
            <p class="form-image-wrapper">
                <img src="<?= $image; ?>?token=<?= time(); ?>"
                     alt="<?= $slug; ?>">
            </p>
            <p>
                <a href="/admin/taxonomy/topics/remove-image/<?= $id; ?>/">
                    Remove image
                </a>
            </p>
        <?php endif; ?>
        <p>
            <span>Image</span>
            <label for="input-image" class="label-input-wrapper">
                <input type="file"
                       name="image"
                       id="input-image">
            </label>
        </p>
        <p>
            <label for="input-parent-id" class="label-input-wrapper">
                <select name="parent_id" id="input-parent-id">
                    <?php
                    $selected = empty($parentId) ? ' selected="selected"' : '';
                    ?>
                    <option value="0" disabled<?= $selected; ?>>
                        Parent
                    </option>
                    <?php if (!empty($topics)): ?>
                        <?php foreach ($topics as $topic): ?>
                            <?php
                            $selected = '';
                            if ($topic->getId() == $parentId) {
                                $selected = ' selected';
                            }
                            ?>
                            <option value="<?= $topic->getId(); ?>"
                                <?= $selected; ?>>
                                <?= $topic->getTitle(); ?>
                            </option>
                        <?php endforeach; ?>
                    <?php endif; ?>
                </select>
            </label>
        </p>
        <p>
            <label for="input-title" class="label-input-wrapper">
                <input type="text"
                       name="title"
                       id="input-title"
                       placeholder="Title"
                       value="<?= $title; ?>">
            </label>
        </p>
        <p>
            <label for="input-slug" class="label-input-wrapper">
                <input type="text"
                       name="slug"
                       id="input-slug"
                       placeholder="Slug"
                       value="<?= $slug; ?>">
            </label>
        </p>
        <p>
            <?php
            $checked = $isActive ? ' checked' : '';
            ?>
            <input type="checkbox"
                   name="is_active"
                   id="input-is-active"
                   value="1"
                <?= $checked ?>>
            <label for="input-is-active">
                Is Active
            </label>
        </p>
        <p>
            <input type="submit" value="save">
        </p>
        <input type="hidden" name="csrf_token" value="<?= $csrfToken ?>">
        <input type="hidden" name="id" value="<?= $id; ?>">
    </form>
</div>
