<?php

use Sonder\Models\Topic\TopicValuesObject;

/* @var TopicValuesObject[]|null $topics */
?>
<p>
    <a href="/admin/taxonomy/tags/">Tags</a> /
    <span>Topics</span>
</p>
<p>
    <a href="/admin/taxonomy/topic/" class="button">New Topic</a>
</p>
<?php if (empty($topics)): ?>
    <p>
        Empty
    </p>
<?php else: ?>
    <table>
        <tbody>
        <tr>
            <th class="fixed-cell hide-on-mobile">ID</th>
            <th>Title</th>
            <th class="hide-on-mobile">Slug</th>
            <th class="hide-on-tablet">Is Active</th>
            <th class="hide-on-mobile">Created At</th>
            <th class="hide-on-tablet">Updated At</th>
            <th class="hide-on-tablet">Removed At</th>
            <th colspan="3"></th>
        </tr>
        <?php foreach ($topics as $topic): ?>
            <?php
            $topicIsActive = $topic->isActive() ? 'Yes' : 'No';

            $topicCdate = $topic->getCdate('Y-m-d H:i:s');

            $topicMdate = '---';
            $topicDdate = '---';

            if (!empty($topic->getMdate())) {
                $topicMdate = $topic->getMdate('Y-m-d H:i:s');
            }

            if (!empty($topic->getDdate())) {
                $topicDdate = $topic->getDdate('Y-m-d H:i:s');
            }
            ?>
            <?php if ($topic->isRemoved()): ?>
                <tr class="list-item-removed">
            <?php else: ?>
                <tr>
            <?php endif; ?>
            <td class="hide-on-mobile"><?= $topic->getId() ?></td>
            <td><?= $topic->getTitle() ?></td>
            <td class="hide-on-mobile"><?= $topic->getSlug() ?></td>
            <td class="hide-on-tablet"><?= $topicIsActive ?></td>
            <td class="hide-on-mobile"><?= $topicCdate ?></td>
            <td class="hide-on-tablet"><?= $topicMdate ?></td>
            <td class="hide-on-tablet"><?= $topicDdate ?></td>
            <td>
                <a href="<?= $topic->getAdminViewLink() ?>">
                    <i class="fas fa-eye"></i>
                </a>
            </td>
            <td>
                <a href="<?= $topic->getEditLink() ?>">
                    <i class="fas fa-edit"></i>
                </a>
            </td>
            <td>
                <?php if ($topic->isRemoved()): ?>
                    <a href="<?= $topic->getRestoreLink() ?>">
                        <i class="fas fa-reply"></i>
                    </a>
                <?php else: ?>
                    <a href="<?= $topic->getRemoveLink() ?>">
                        <i class="fas fa-trash-alt"></i>
                    </a>
                <?php endif; ?>
            </td>
            </tr>
        <?php endforeach; ?>
        <tr>
            <th class="fixed-cell hide-on-mobile">ID</th>
            <th>Title</th>
            <th class="hide-on-mobile">Slug</th>
            <th class="hide-on-tablet">Is Active</th>
            <th class="hide-on-mobile">Created At</th>
            <th class="hide-on-tablet">Updated At</th>
            <th class="hide-on-tablet">Removed At</th>
            <th colspan="3"></th>
        </tr>
        </tbody>
    </table>
<?php endif; ?>
<?php if (!empty($pagination)): ?>
    <div class="pagination">
        <?= $pagination ?>
    </div>
<?php endif; ?>
