<?php
/* @var TopicValuesObject[]|null $topics */
?>
<a href="/admin/topic/" class="button">New topic</a>

<?php if (empty($topics)): ?>
    Empty...
<?php else: ?>
    <table>
        <tbody>
        <tr>
            <th class="fixed-cell hide-on-mobile">ID</th>
            <th>Title</th>
            <th class="hide-on-tablet">Slug</th>
            <th class="hide-on-tablet">Language</th>
            <th class="hide-on-mobile">Created At</th>
            <th class="hide-on-tablet">Updated At</th>
            <th class="hide-on-tablet">Removed At</th>
            <th colspan="3"></th>
        </tr>
        <?php foreach ($topics as $topic): ?>
            <?php
            $topicCdate = date('Y-m-d H:i:s', $topic->getCdate());

            $topicMdate = '---';
            $topicDdate = '---';

            if (!empty($topic->getMdate())) {
                $topicMdate = date('Y-m-d H:i:s', $topic->getMdate());
            }

            if (!empty($topic->getDdate())) {
                $topicDdate = date('Y-m-d H:i:s', $topic->getDdate());
            }
            ?>
            <?php if ($topic->isRemoved()): ?>
                <tr class="list-item-removed">
            <?php else: ?>
                <tr>
            <?php endif; ?>
            <td class="hide-on-mobile"><?= $topic->getId(); ?></td>
            <td><?= $topic->getTitle(); ?></td>
            <td class="hide-on-tablet"><?= $topic->getSlug(); ?></td>
            <td class="hide-on-tablet"><?= $topic->getLanguage(); ?></td>
            <td class="hide-on-mobile"><?= $topicCdate ?></td>
            <td class="hide-on-tablet"><?= $topicMdate; ?></td>
            <td class="hide-on-tablet"><?= $topicDdate; ?></td>
            <td>
                <?php if (!$topic->isRemoved()): ?>
                    <a href="<?= $topic->getLink(); ?>" target="_blank">
                        <i class="fas fa-eye"></i>
                    </a>
                <?php endif; ?>
            </td>
            <td>
                <a href="<?= $topic->getEditLink(); ?>">
                    <i class="fas fa-edit"></i>
                </a>
            </td>
            <td>
                <?php if ($topic->isRemoved()): ?>
                    <a href="<?= $topic->getRestoreLink(); ?>">
                        <i class="fas fa-reply"></i>
                    </a>
                <?php else: ?>
                    <a href="<?= $topic->getRemoveLink(); ?>">
                        <i class="fas fa-trash-alt"></i>
                    </a>
                <?php endif; ?>
            </td>
            </tr>
        <?php endforeach; ?>
        <tr>
            <th class="fixed-cell hide-on-mobile">ID</th>
            <th>Title</th>
            <th class="hide-on-tablet">Slug</th>
            <th class="hide-on-tablet">Language</th>
            <th class="hide-on-mobile">Created At</th>
            <th class="hide-on-tablet">Updated At</th>
            <th class="hide-on-tablet">Removed At</th>
            <th colspan="3"></th>
        </tr>
        </tbody>
    </table>
<?php endif; ?>
