<?php
/* @var string|null $csrfToken */
/* @var int|null $id */
/* @var string|null $action */
/* @var int|null $interval */
/* @var bool $isActive */
/* @var array|null $errors */

$formAction = '/admin/settings/cron/job/';

if (!empty($id)) {
    $formAction = sprintf('/admin/settings/cron/job/%d/', $id);
}
?>
<p>
    <a href="/admin/settings/cache/">Cache</a> /
    <a href="/admin/settings/cron/">Cron</a> /
    <a href="/admin/settings/configs/">Configs</a>
</p>
<div class="form-wrapper">
    <?php if (empty($id)): ?>
        <h1>Add New Cron Job</h1>
    <?php else: ?>
        <h1>Edit Cron Job</h1>
    <?php endif; ?>
    <?php if (!empty($errors)): ?>
        <div class="errors">
            <?php foreach ($errors as $error): ?>
                <p>
                    <?= $error; ?>
                </p>
            <?php endforeach; ?>
        </div>
    <?php endif; ?>
    <form action="<?= $formAction; ?>" method="POST">
        <p>
            <label for="input-name" class="label-input-wrapper">
                <input type="text"
                       name="action"
                       id="input-action"
                       placeholder="Action"
                       value="<?= $action; ?>">
            </label>
        </p>
        <p>
            <label for="input-interval" class="label-input-wrapper">
                <input type="number"
                       name="interval"
                       id="input-interval"
                       placeholder="Interval"
                       value="<?= $interval; ?>">
            </label>
        </p>
        <p>
            <?php
            $checked = $isActive ? ' checked' : '';
            ?>
            <input type="checkbox"
                   name="is_active"
                   id="input-is-active"
                   value="1"
                <?= $checked ?>>
            <label for="input-is-active">
                Is Active
            </label>
        </p>
        <p>
            <input type="submit" value="save">
        </p>
        <input type="hidden" name="csrf_token" value="<?= $csrfToken ?>">
        <input type="hidden" name="id" value="<?= $id; ?>">
    </form>
</div>
