<?php
/* @var string|null $csrfToken */
/* @var int|null $id */
/* @var string|null $login */
/* @var string|null $password */
/* @var string|null $apiToken */
/* @var bool $isAllowAccessByApi */
/* @var array|null $errors */

$formAction = sprintf('/admin/users/credentials/%d/', $id);
?>
<p>
    <a href="/admin/users/">Users</a> /
    <a href="/admin/users/roles/">Roles</a> /
    <a href="/admin/users/roles/actions/">Actions</a>
</p>
<h1>Credentials For User &#xab;<?= $login; ?>&#xbb; (ID: <?= $id; ?>)</h1>
<div class="form-wrapper">
    <?php if (!empty($errors)): ?>
        <div class="errors">
            <?php foreach ($errors as $error): ?>
                <p>
                    <?= $error; ?>
                </p>
            <?php endforeach; ?>
        </div>
    <?php endif; ?>
    <form action="<?= $formAction; ?>"
          enctype="multipart/form-data"
          method="POST">
        <p>
            <label for="input-login" class="label-input-wrapper">
                <input type="text"
                       name="login"
                       id="input-login"
                       placeholder="Login"
                       value="<?= $login; ?>">
            </label>
        </p>
        <p>
            <label for="input-password" class="label-input-wrapper">
                <input type="text"
                       name="password"
                       name="input-password"
                       placeholder="Password"
                       value="<?= $password; ?>">
            </label>
        </p>
        <?php if (!empty($apiToken)): ?>
            <p>
                API Token
            </p>
            <p>
                <?= $apiToken; ?>
            </p>
        <?php endif; ?>
        <p>
            <?php
            $checked = $isAllowAccessByApi ? ' checked' : '';
            ?>
            <input type="checkbox"
                   name="is_allow_access_by_api"
                   id="input-is-allow-access-by-api"
                   value="1"
                <?= $checked ?>>
            <label for="input-is-allow-access-by-api">
                Is Allow Access By API
            </label>
        </p>
        <p>
            <input type="submit" value="save">
        </p>
        <input type="hidden" name="csrf_token" value="<?= $csrfToken ?>">
        <input type="hidden" name="id" value="<?= $id; ?>">
    </form>
</div>
