<?php
/* @var string|null $csrfToken */
/* @var int|null $id */
/* @var string|null $login */
/* @var string|null $email */
/* @var string|null $password */
/* @var int|null $roleId */
/* @var array|null $roles */
/* @var bool $isAllowAccessByApi */
/* @var bool $isActive */
/* @var array|null $errors */

$formAction = '/admin/user/';

if (!empty($id)) {
    $formAction = sprintf('/admin/user/%d/', $id);
}
?>
<p>
    <a href="/admin/users/">Users</a> /
    <a href="/admin/users/roles/">Roles</a> /
    <a href="/admin/users/roles/actions/">Actions</a>
</p>
<?php if (empty($id)): ?>
    <h1>Add New User</h1>
<?php else: ?>
    <h1>Edit User</h1>
<?php endif; ?>
<div class="form-wrapper">
    <?php if (!empty($errors)): ?>
        <div class="errors">
            <?php foreach ($errors as $error): ?>
                <p>
                    <?= $error; ?>
                </p>
            <?php endforeach; ?>
        </div>
    <?php endif; ?>
    <form action="<?= $formAction; ?>"
          enctype="multipart/form-data"
          method="POST">
        <p>
            <?php if (empty($id)): ?>
                <label for="input-login" class="label-input-wrapper">
                    <input type="text"
                           name="login"
                           id="input-login"
                           placeholder="Login"
                           value="<?= $login; ?>">
                </label>
            <?php else: ?>
                Login: <?= $login ?>
                <input type="hidden" name="login" value="<?= $login; ?>">
            <?php endif; ?>
        </p>
        <p>
            <label for="input-email" class="label-input-wrapper">
                <input type="text"
                       name="email"
                       id="input-email"
                       placeholder="Email"
                       value="<?= $email; ?>">
            </label>
        </p>
        <p>
            <label for="input-role-id" class="label-input-wrapper">
                <select name="role_id" id="input-role-id">
                    <?php
                    $selected = empty($parentId) ? ' selected="selected"' : '';
                    ?>
                    <option value="0" disabled<?= $selected; ?>>
                        Role
                    </option>
                    <?php if (!empty($roles)): ?>
                        <?php foreach ($roles as $role): ?>
                            <?php
                            $selected = '';
                            if ($role->getId() == $roleId) {
                                $selected = ' selected';
                            }
                            ?>
                            <option value="<?= $role->getId(); ?>"
                                <?= $selected; ?>>
                                <?= $role->getName(); ?>
                            </option>
                        <?php endforeach; ?>
                    <?php endif; ?>
                </select>
            </label>
        </p>
        <?php if (empty($id)): ?>
            <p>
                <label for="input-password" class="label-input-wrapper">
                    <input type="text"
                           name="password"
                           id="input-password"
                           placeholder="Password"
                           value="<?= $password; ?>">
                </label>
            </p>
            <p>
                <?php
                $checked = $isAllowAccessByApi ? ' checked' : '';
                ?>
                <input type="checkbox"
                       name="is_allow_access_by_api"
                       id="input-is-allow-access-by-api"
                       value="1"
                    <?= $checked ?>>
                <label for="input-is-allow-access-by-api">
                    Is Allow Access By API
                </label>
            </p>
        <?php else: ?>
            <p>
                <a href="/admin/users/credentials/<?= $id; ?>/">Credentials</a>
            </p>
        <?php endif; ?>
        <p>
            <?php
            $checked = $isActive ? ' checked' : '';
            ?>
            <input type="checkbox"
                   name="is_active"
                   id="input-is-active"
                   value="1"
                <?= $checked ?>>
            <label for="input-is-active">
                Is Active
            </label>
        </p>
        <p>
            <input type="submit" value="save">
        </p>
        <input type="hidden" name="csrf_token" value="<?= $csrfToken ?>">
        <input type="hidden" name="id" value="<?= $id; ?>">
    </form>
</div>
