<?php

use Sonder\Models\User\UserValuesObject;

/* @var UserValuesObject[]|null $users */
?>
<p>
    <span>Users</span> /
    <a href="/admin/users/roles/">Roles</a> /
    <a href="/admin/users/roles/actions/">Actions</a>
</p>
<p>
    <a href="/admin/user/" class="button">New User</a>
</p>
<?php if (empty($users)): ?>
    <p>
        Empty
    </p>
<?php else: ?>
    <table>
        <tbody>
        <tr>
            <th class="fixed-cell hide-on-mobile">ID</th>
            <th>Login</th>
            <th class="hide-on-mobile">Role</th>
            <th class="hide-on-tablet">Is Active</th>
            <th class="hide-on-mobile">Created At</th>
            <th class="hide-on-tablet">Updated At</th>
            <th class="hide-on-tablet">Removed At</th>
            <th colspan="4"></th>
        </tr>
        <?php foreach ($users as $user): ?>
            <?php
            $userIsActive = $user->getIsActive() ? 'Yes' : 'No';

            $userCdate = $user->getCdate('Y-m-d H:i:s');

            $userMdate = '---';
            $userDdate = '---';

            if (!empty($user->getMdate())) {
                $userMdate = $user->getMdate('Y-m-d H:i:s');
            }

            if (!empty($user->getDdate())) {
                $userDdate = $user->getDdate('Y-m-d H:i:s');
            }
            ?>
            <?php if ($user->isRemoved()): ?>
                <tr class="list-item-removed">
            <?php else: ?>
                <tr>
            <?php endif; ?>
            <td class="hide-on-mobile"><?= $user->getId(); ?></td>
            <td><?= $user->getLogin(); ?></td>
            <td class="hide-on-mobile">
                <?= $user->getRoleVO()->getName(); ?>
            </td>
            <td class="hide-on-tablet"><?= $userIsActive; ?></td>
            <td class="hide-on-mobile"><?= $userCdate; ?></td>
            <td class="hide-on-tablet"><?= $userMdate; ?></td>
            <td class="hide-on-tablet"><?= $userDdate; ?></td>
            <td>
                <a href="<?= $user->getAdminViewLink(); ?>">
                    <i class="fas fa-eye"></i>
                </a>
            </td>
            <td>
                <a href="<?= $user->getEditLink(); ?>">
                    <i class="fas fa-edit"></i>
                </a>
            </td>
            <td>
                <a href="<?= $user->getAdminCredentialsLink(); ?>">
                    <i class="fas fa-lock"></i>
                </a>
            </td>
            <td>
                <?php if ($user->isRemoved()): ?>
                    <a href="<?= $user->getRestoreLink(); ?>">
                        <i class="fas fa-reply"></i>
                    </a>
                <?php else: ?>
                    <a href="<?= $user->getRemoveLink(); ?>">
                        <i class="fas fa-trash-alt"></i>
                    </a>
                <?php endif; ?>
            </td>
            </tr>
        <?php endforeach; ?>
        <tr>
            <th class="fixed-cell hide-on-mobile">ID</th>
            <th>Login</th>
            <th class="hide-on-mobile">Role</th>
            <th class="hide-on-tablet">Is Active</th>
            <th class="hide-on-mobile">Created At</th>
            <th class="hide-on-tablet">Updated At</th>
            <th class="hide-on-tablet">Removed At</th>
            <th colspan="4"></th>
        </tr>
        </tbody>
    </table>
<?php endif; ?>
<?php if (!empty($pagination)): ?>
    <div class="pagination">
        <?= $pagination ?>
    </div>
<?php endif; ?>
