<?php
/* @var PostValuesObject[]|null $posts */
?>
<p>
    <a href="/admin/user/" class="button">New user</a>
</p>
<p>
    <a href="/admin/users/roles/" class="button">Roles</a>
</p>
<?php if (empty($posts)): ?>
    Empty...
<?php else: ?>
    <table>
        <tbody>
        <tr>
            <th class="fixed-cell hide-on-mobile">ID</th>
            <th>Title</th>
            <th class="hide-on-tablet">Slug</th>
            <th class="hide-on-tablet">Topic</th>
            <th class="hide-on-tablet">Image</th>
            <th class="hide-on-tablet">Language</th>
            <th class="hide-on-mobile">Created At</th>
            <th class="hide-on-tablet">Updated At</th>
            <th class="hide-on-tablet">Removed At</th>
            <th colspan="3"></th>
        </tr>
        <?php foreach ($posts as $post): ?>
            <?php
            $postCdate = date('Y-m-d H:i:s', $post->getCdate());

            $postMdate = '---';
            $postDdate = '---';

            $postTopic = '---';

            if (!empty($post->getMdate())) {
                $postMdate = date('Y-m-d H:i:s', $post->getMdate());
            }

            if (!empty($post->getDdate())) {
                $postDdate = date('Y-m-d H:i:s', $post->getDdate());
            }

            if (!empty($post->getTopic())) {
                $postTopic = $post->getTopic()->getTitle();
            }
            ?>
            <?php if ($post->isRemoved()): ?>
                <tr class="list-item-removed">
            <?php else: ?>
                <tr>
            <?php endif; ?>
            <td class="hide-on-mobile"><?= $post->getId(); ?></td>
            <td><?= $post->getTitle(); ?></td>
            <td class="hide-on-tablet"><?= $post->getSlug(); ?></td>
            <td class="hide-on-tablet"><?= $postTopic; ?></td>
            <td class="hide-on-tablet">
                <a href="<?= $post->getMedia(); ?>"
                   target="_blank"
                   class="post-list-image-wrapper">
                    <img src="<?= $post->getMedia('thumbnail'); ?>"
                         alt="image"
                         class="post-list-image"/>
                </a>
            </td>
            <td class="hide-on-tablet"><?= $post->getLanguage(); ?></td>
            <td class="hide-on-mobile"><?= $postCdate ?></td>
            <td class="hide-on-tablet"><?= $postMdate; ?></td>
            <td class="hide-on-tablet"><?= $postDdate; ?></td>
            <td>
                <?php if (!$post->isRemoved()): ?>
                    <a href="<?= $post->getLink(); ?>" target="_blank">
                        <i class="fas fa-eye"></i>
                    </a>
                <?php endif; ?>
            </td>
            <td>
                <a href="<?= $post->getEditLink(); ?>">
                    <i class="fas fa-edit"></i>
                </a>
            </td>
            <td>
                <?php if ($post->isRemoved()): ?>
                    <a href="<?= $post->getRestoreLink(); ?>">
                        <i class="fas fa-reply"></i>
                    </a>
                <?php else: ?>
                    <a href="<?= $post->getRemoveLink(); ?>">
                        <i class="fas fa-trash-alt"></i>
                    </a>
                <?php endif; ?>
            </td>
            </tr>
        <?php endforeach; ?>
        <tr>
            <th class="fixed-cell hide-on-mobile">ID</th>
            <th>Title</th>
            <th class="hide-on-tablet">Slug</th>
            <th class="hide-on-tablet">Topic</th>
            <th class="hide-on-tablet">Image</th>
            <th class="hide-on-tablet">Language</th>
            <th class="hide-on-mobile">Created At</th>
            <th class="hide-on-tablet">Updated At</th>
            <th class="hide-on-tablet">Removed At</th>
            <th colspan="3"></th>
        </tr>
        </tbody>
    </table>
<?php endif; ?>
<?php if (!empty($pagination)): ?>
    <div class="pagination">
        <?= $pagination; ?>
    </div>

<?php endif; ?>
